/// Flutter icons StakePoolLotto
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StakePoolLotto
///      fonts:
///       - asset: fonts/StakePoolLotto.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SPDIcons {
  const SPDIcons._();
  static const _kFontFam = 'StakePoolLotto';
  static const String? _kFontPkg = null;
  static const IconData account = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowdown = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowleft = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowright = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowup = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrondown = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronleft = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronright = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronup = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamationmark = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reverse = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sol = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
